### PR TITLE
bump infrastructure-bundle to 1.6.0

### PR DESCRIPTION
**Pull request by roobre**
This PR bumps infrastructure-bundle base version to `1.6.0`.

Remarkably, this also fixes JSON pointed by [new relic docs](https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/installation/install-ecs-integration) to point to `infrastructure-bundle:1.6.0`, which includes the fix for https://github.com/newrelic/nri-docker/issues/49

### CODE REVIEW

**Review by arvdias — APPROVED** [review]

**Review by paologallinaharbur — DISMISSED** [review]
Only a small comment, in the last similar PR they updated also the expected version of the integration, should we do the same?
https://github.com/newrelic/nri-ecs/pull/4/files

**Comment by roobre** [comment]
> Only a small comment, in the last similar PR they updated also the expected version of the integration, should we do the same?
> https://github.com/newrelic/nri-ecs/pull/4/files

So... I'm not really sure. Perhaps @alejandrodnm can tell us if this should be done?

**Comment by alejandrodnm** [comment]
You need to update the integration version here https://github.com/newrelic/nri-ecs/blob/main/pkg/ecs/integration.go#L13 and that will break your tests, because we assert on the whole payload.

That value is the one used by the integration agent to decorate the integration samples.

**Review by alejandrodnm — APPROVED** [review]
You have the TODO: fix date, but other than that LGTM

**Review by alejandrodnm — APPROVED** [review]

**Comment by roobre** [comment]
> You have the TODO: fix date, but other than that LGTM

Good catch, thanks for the ultra-fast re-review! ❤️

**Pull request merged**
